version: '3.4'

services:

  postgresql:
    image: postgres:14.1

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: System\Api\WebApi\Dockerfile
    depends_on:
      - postgresql
