version: '3.4'

services:

  postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=meow
    ports:
      - "5430:5430"
    command: 
      - "postgres"
      - "-c"
      - "port=5430"
    networks:
      - shared_quotations_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  webapi:
    ports:
      - "10000:80"
    networks:
      - shared_quotations_net
    env_file:
      - env.api

networks:
  shared_quotations_net:
    name: quotations
    driver: bridge